name: mnms2
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.10
  - numpy==1.19.5
  - scikit-image==0.16.2
  - cudatoolkit==11.0.221
  - cudnn==8.0.5.39
  - scipy==1.4.1
  - matplotlib
  - pip
  - pip:
      - tensorflow==2.5.0
      - tensorflow-addons==0.13.0
      - simpleitk==2.0.2
      - voxelmorph==0.1

