name: mnms2
channels:
  - defaults
dependencies:
  - python==3.10.11
  - scikit-image==0.24.0
  - scikit-learn==1.5.1
  - matplotlib==3.9.2
  - pip
  - pip:
      - tensorflow[and-cuda]==2.17.0
      - tensorflow-addons==0.23.0
      - simpleitk==2.4.0
      - voxelmorph==0.2
